### PR TITLE
Refactor/121 eslint issues

### PR DESCRIPTION
**Pull request by AllenBW**
Resolves: 
* indentation and dangling comma
* angular/contorller-as
* no-unused-vars
* no-useless-concat

## Before
screen shot 2016-09-21 at 5 03 17 pm

## After
screen shot 2016-09-21 at 5 02 29 pm

shoutout to #121

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@AllenBW can you fix up the conflicts?

**Comment by AllenBW** [comment]
@chriskacerguis 🔨

**Comment by chriskacerguis** [comment]
@AllenBW another conflict

**Comment by dtaylor113** [comment]
Hi @AllenBW , how was the rule "angular/contorller-as" resolved in this PR?
I just thought I had some work to do to the blueprint controllers to fix this rule.
Thanks,
- Dave

**Comment by AllenBW** [comment]
@dtaylor113 resolved by adding ignores to the files in need of attention for the time being, totally not a long term solution, but when we turn this on, it'll stop prs from going in should anyone touch the file..

**Comment by dtaylor113** [comment]
Ok, got it.  Thanks for the explanation :-)

**Comment by AllenBW** [comment]
@dtaylor113 thanks for the sanity check!  i'll work on being more clear on why whats going on is going on <3

**Comment by chessbyte** [comment]
@chriskacerguis This did not make it into Euwe branch. Please label euwe/yes or euwe/no, as appropriate.

**Pull request merged**
