### PR TITLE
Removed unused title from Requests details state

### PR DESCRIPTION
**Pull request by romanblanco**
I can't find any place in UI that would use this title

### CODE REVIEW

**Comment by dclarizio** [comment]
@himdel @AparnaKarve please verify, then I can merge.

**Comment by AparnaKarve** [comment]
@dclarizio LGTM :+1:

**Comment by himdel** [comment]
LGTM.. though it seems like every `vm.title = ...` in `**/*.state.js` is also unused

**Comment by dclarizio** [comment]
@romanblanco If you want to look into the others per @himdel in another PR, that's fine . . . merging this one.

**Pull request merged**
