### PR TITLE
Implemented WebSocket token requesting mechanism for Notifications

### PR DESCRIPTION
**Pull request by skateman**

### CODE REVIEW

**Comment by himdel** [comment]
LGTM, verified that this does open a websocket connection that doesn't die because of authentication problems (doesn't die at all :+1: )

**Comment by skateman** [comment]
LOL

**Comment by chessbyte** [comment]
Euwe Backport conflict:
```sh
$ git cherry-pick -e -x -m 1  f11c854
error: could not apply f11c854... Merge pull request #202 from skateman/request-ws-token
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'

$ git status
On branch euwe
Your branch is up-to-date with 'upstream/euwe'.
You are currently cherry-picking commit f11c854.
  (fix conflicts and run "git cherry-pick --continue")
  (use "git cherry-pick --abort" to cancel the cherry-pick operation)

Changes to be committed:

	modified:   bower.json
	modified:   client/app/services/services.module.js
	modified:   client/app/services/session.service.js
	modified:   tests/session.service.spec.js

Unmerged paths:
  (use "git add <file>..." to mark resolution)

	both modified:   client/app/states/login/login.state.js

$ git diff
```

```diff
diff --cc client/app/states/login/login.state.js
index 62bf3d7,45aa89d..0000000
--- a/client/app/states/login/login.state.js
+++ b/client/app/states/login/login.state.js
@@@ -49,6 -49,8 +49,11 @@@
  
        return AuthenticationApi.login(vm.credentials.login, vm.credentials.password)
          .then(Session.loadUser)
++<<<<<<< HEAD
++=======
+         .then(Session.requestWsToken)
+         .then(ServerInfo.set)
++>>>>>>> f11c854... Merge pull request #202 from skateman/request-ws-token
          .then(Language.onLogin)
          .then(function() {
            if (Session.activeNavigationFeatures()) {
```

**Comment by chessbyte** [comment]
Euwe Backport details:
```sh
$ git log
commit 2035011873b1f57877da5d3e18eb8fb94a038528
Author: Martin Hradil <himdel@seznam.cz>
Date:   Fri Sep 30 19:26:47 2016 +0200

    Merge pull request #202 from skateman/request-ws-token
    
    Implemented WebSocket token requesting mechanism for Notifications
    (cherry picked from commit f11c854f1a964d6fd73594cf126fb0000e477956)
```

**Pull request merged**
