### PR TITLE
[WIP] npm - update everything

### LINKED ISSUE #59: Address npm dependency issues found in darga branch
<p>bitHound discovered:</p> <ul> <li>4 packages with at least one security vulnerability.</li> <li>5 deprecated packages.</li> <li>31 outdated packages.</li> </ul> <p>For details go to <a href="https://www.bithound.io/github/ManageIQ/manageiq-ui-self_service/darga/dependencies/npm">bitHound</a>.</p> 
***
These insecure Dev packages found by Bithound might need to be updated for a product release. Also, there are 31 outdated packages that will only get more outdated.

-- Mike Thompson

### PR DESCRIPTION
**Pull request by himdel**
Cleans up & updates npm dependencies..

Closes #59

### CODE REVIEW

**Comment by himdel** [comment]
notes...

wiredep 2.2.2 > 3.0 (and 4.0) - breaks order of jquery

**Comment by chriskacerguis** [comment]
@himdel would you like me to have @AllenBW finish this, or would can you get this over?

**Comment by himdel** [comment]
@chriskacerguis depends, I probably won't be able to do this in the next few weeks, so.. @AllenBW how much time do you have? ;)

**Comment by chriskacerguis** [comment]
@himdel I'll get @AllenBW to do his mojo and update everything.

**Comment by chriskacerguis** [comment]
Closing this PR, I moved this to a new issue https://github.com/ManageIQ/manageiq-ui-self_service/issues/143

**Pull request closed without merging**
