### PR TITLE
Add Requester filter to My Requests

### PR DESCRIPTION
**Pull request by bmclaughlin**
Added a Requester column, filter and sort to My Requests.

https://bugzilla.redhat.com/show_bug.cgi?id=1343722

### CODE REVIEW

**Comment by bmclaughlin** [comment]
Before:
ssui-before

After:
ssui-after

**Comment by AparnaKarve** [comment]
LGTM.
Verified in UI as well 👍

**Comment by bmclaughlin** [comment]
Amended the commit to reference the upstream BZ.

**Comment by chessbyte** [comment]
Darga Backport details:
```sh
$ git cherry-pick -x -m 1 b8adb49 
[darga b630e70] Merge pull request #104 from bmclaughlin/add-requester-filter
 Author: Dan Clarizio <dclarizi@redhat.com>
 Date: Mon Aug 29 13:11:58 2016 -0700
 2 files changed, 23 insertions(+), 3 deletions(-)

$ git log
commit b630e704da72a2b90ab569d90830e8462116699d
Author: Dan Clarizio <dclarizi@redhat.com>
Date:   Mon Aug 29 13:11:58 2016 -0700

    Merge pull request #104 from bmclaughlin/add-requester-filter
    
    Add Requester filter to My Requests
    (cherry picked from commit b8adb49ccf3e0caa1f20cd1703f272365b73aed0)
```

**Pull request merged**
