### PR TITLE
Add Edit capability for Designer Rules

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
This PR add the ability to edit designer rules. The user can set the fields and drag & drop rules to order by priority.

image

cc @serenamarie125 @beanh66 @dtaylor113 @chriskacerguis

### CODE REVIEW

**Comment by dtaylor113** [comment]
LGTM.  Jeff you need to fix the TravisCI error.  To run it locally type 'gulp vet'.

**Comment by chriskacerguis** [comment]
@jeff-phillips-18 is this ready to be reviewed / merged?

**Comment by jeff-phillips-18** [comment]
@chriskacerguis  Yes, sorry for the churn but I believe it is all set now.

**Comment by chriskacerguis** [comment]
@jeff-phillips-18 FYI - When just working on something we add the [WIP] prefix (work in progress) then when it's ready we remove the label.

**Pull request merged**
