### PR TITLE
Adds eslint dependencies and preliminary rules

### PR DESCRIPTION
**Pull request by AllenBW**
Extending jshint, includes angular specific best practices and check as well.

I know everyone is busy, but ideally this is more of a conversation than a pr @himdel (if you have a sec) or anyone in general :)  

It is known that we are using airbnb eslint elsewhere: https://github.com/ManageIQ/manageiq/blob/62186766366eae2e93ba1300abe85fc3d8377482/package.json  so the question has to be asked, are we ok doing something different here? (semi rhetorical question I believe yes, because architecturally this is a different beast)

#121 is one bullet closer to complete with this pr

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@Fryguy any issues here?

**Comment by chriskacerguis** [comment]
@himdel any thoughts / issues here?

**Comment by AparnaKarve** [comment]
@AllenBW Am I correct in my understanding that this would be more handy in the future when we upgrade to Angular 2 and as a result we would be coding more in `es6`?

**Comment by AllenBW** [comment]
@AparnaKarve heeeeeeeey you noticed that :P yeah es6 is one of the style envs we're targeting with this, the thought being that the forward leaning will be of great benefit the future.  In general though the move to using eslint, stronger code style checks is of great benefit now.  To no single persons fault ( 👊 collective) ssui is wee bit messy.

**Comment by himdel** [comment]
I'd be definitely for keeping this eslint and manageiq's eslint config similar, or as close to similar as makes sense. But you're right this is a different beast, so.. :)

**Pull request merged**
