### PR TITLE
Bug/eslint unused vars multiline vars

### PR DESCRIPTION
**Pull request by AllenBW**
Resolves unused and multiline vars
## Before
screen shot 2016-09-15 at 4 54 50 pm

## After
screen shot 2016-09-15 at 4 53 52 pm

Holla holla #121 (issue that is tracking these changes)

### CODE REVIEW

**Comment by dtaylor113** [comment]
Hi, LGTM, but please don't merge until I can test blueprint functionality against this branch.  Should be able to do it first thing tomorrow morning.  -thanks

**Comment by chriskacerguis** [comment]
@dtaylor113 I'll hold on the merge, but if you wouldn't mind in the future, can you please not add your approval until it is ready to go...it becomes too hard to manage PR's.

/cc @AllenBW @serenamarie125

**Comment by dtaylor113** [comment]
@chriskacerguis , ok, but I didn't Approve this PR yet ?

**Comment by dtaylor113** [comment]
Ok, just smoke tested this branch.

**Comment by chriskacerguis** [comment]
Then I mis interpret your LGTM comment above

**Comment by dtaylor113** [comment]
Ok, no worries, I'll be clearer in the future :-)

**Pull request merged**
