### PR TITLE
Translation fixes

### PR DESCRIPTION
**Pull request by mzazrivec**
These are fixes to make sure:
* the strings to translate do not contain html markup
* the string to translate do not contain unnecessary newlines

@himdel Please review

@chriskacerguis These are things that need to be caught at a PR review.

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@mzazrivec not sure, I'm following your comment.  Could you please clarify what you mean?

**Comment by mzazrivec** [comment]
@chriskacerguis I mean that correct use of translate needs to be reviewed more carefully, fixing this
once it's merged is not quite easy (the ssui application becomes larger and larger).

I'm taggin you since you merged these PRs.

**Comment by AllenBW** [comment]
totally agree with ya @mzazrivec, we gotta be vigilante when it comes to ensuring sui is properly setup for translations (totally shoulda been on my radar before, but now it is)

currently chewing on some ideas for incorporating the gettext-extract gulp task into build, it would be kinda neat to review the build, identify missing translations and flag them/make it a fixme before a pr could be merged...

**Comment by chriskacerguis** [comment]
@mzazrivec good point, is there a document we can point people to?

**Comment by mzazrivec** [comment]
@chriskacerguis There's i18n documentation for ManageIQ as well as documentation of
the angular-gettext module that explains how to annotate strings for translations.

We did not have any documentation on what not to do, so yes, I created https://github.com/ManageIQ/guides/pull/152
adding just that (although I don't see how would the lack of documentation like that make
fixes from this PR any less valid).

**Comment by mzazrivec** [comment]
@AllenBW I'm with you on the automatic detection of problematic stuff. So catching incorrectly
placed `translate` could be a matter of running `gulp gettext-extract` and looking for html markup
in the resulting `.pot` file.

The other problems would be more difficult to catch.

Strings that won't be collected because of dynamic content -- we'd have to hook into the collection
process somehow to see what wasn't included.

Detecting places where the translation annotation is missing -- almost impossible to do automatically.
Although marking the strings that went through gettext, as we do in the ManageIQ application, would
help a great deal here.

**Comment by martinpovolny** [comment]
@chriskacerguis : I am merging this. We need the catalogs to be updated asap for the translators. 

I don't get how this particular PR is blocked by the requirement to provide more documentation for the i18n. You are not requesting changes to this particular PR, right? Sorry if I misunderstood.

@mzazrivec : please, find the time to provide more detailed info regarding i18n. Thx!

**Comment by martinpovolny** [comment]
Ahh, right, the docs is here: ManageIQ/guides#152

**Comment by chessbyte** [comment]
Euwe Backport details:
```sh
$ git log
commit 03f5168814ed19a8c815898d2d911274e1aba770
Author: Martin Povolny <mpovolny@redhat.com>
Date:   Mon Sep 26 14:30:09 2016 +0200

    Merge pull request #182 from mzazrivec/translation_fixes
    
    Translation fixes
    (cherry picked from commit 1234e29f338da5be8863ed7f37a01ac2e9024a66)
```

**Pull request merged**
