### PR TITLE
Product logo not displayed on login screen

### PR DESCRIPTION
**Pull request by epwinchell**
Depends on: https://github.com/ManageIQ/manageiq-ui-self_service/pull/116
https://bugzilla.redhat.com/show_bug.cgi?id=1366357

Old
screen shot 2016-09-06 at 3 50 57 pm

New
screen shot 2016-09-06 at 3 49 45 pm

### CODE REVIEW

**Comment by epwinchell** [comment]
@miq-bot add_label bug, darga/yes

**Comment by epwinchell** [comment]
@miq-bot assign @dclarizio

**Comment by epwinchell** [comment]
cc @serenamarie125

**Comment by serenamarie125** [comment]
Excellent, thanks @epwinchell

**Comment by himdel** [comment]
(Tests should pass when #118 is merged..)

**Comment by himdel** [comment]
LGTM, also, works :)

**Comment by chessbyte** [comment]
Darga Backport details:
```sh
$ git cherry-pick -x -m 1  6fbcc6b     
[darga ea14730] Merge pull request #117 from epwinchell/login_logo
 Author: Martin Hradil <himdel@seznam.cz>
 Date: Wed Sep 7 08:40:24 2016 +0000
 1 file changed, 3 insertions(+)

$ git log
commit ea14730bb213423128137e5eb74095a77e20f878
Author: Martin Hradil <himdel@seznam.cz>
Date:   Wed Sep 7 08:40:24 2016 +0000

    Merge pull request #117 from epwinchell/login_logo
    
    Product logo not displayed on login screen
    (cherry picked from commit 6fbcc6bb2f3154aa762c7bb4ca5474da91221fb5)
```

**Pull request merged**
