### PR TITLE
Resolves eslint "You should not set properties on $scope in controlle…

### PR DESCRIPTION
**Pull request by AllenBW**
Resolves eslint "You should not set properties on $scope in controllers"
(pushes all things local to a component onto `vm` an alias for `this`. This keeps us from polluting scope.

Resolves eslint DI-IN (dependency injection) form absent from components
(principally makes ssui minification hardy, but also for the curious https://en.wikipedia.org/wiki/Dependency_injection)

@dtaylor113 don't hate me
also, if you get a hot sec, could you drop in on this branch and confirm I didn't make a royal mess? 🙏 🙇 :feelsgood: 

#121 is inched ahead just a bit farther, there are a number of eslint errors outstanding, wanted to tackle hairier ones first

### CODE REVIEW

**Comment by chriskacerguis** [comment]
👍

**Comment by dtaylor113** [comment]
Hi @AllenBW & @chriskacerguis, umm...yeah, this PR royally clobbered my files.  It is going to take me a while to merge this with my latest branches  I can't even understand what happened to editorCtrls.js:  https://github.com/ManageIQ/manageiq-ui-self_service/pull/126/files#diff-14924860d0c7815b3c18fdf581826666 :sob:

**Comment by dtaylor113** [comment]
I understand the rest of the file changes, switching $scope to vm, but something really went wrong in editorCtrls.js, it's not even the same function names?!

**Comment by AllenBW** [comment]
@dtaylor113 oh shiiii, something went south when i rebased onto master, so right in calling out `editorCtrls.js`  please trash whats there, restore the original kill $scope for vm (or I can) again, sorry about the mess :-/

**Comment by dtaylor113** [comment]
Ok, no worries, that's what I ended up doing for this PR.  I'll have to go through it again in my other dev branch, but that's the risk one takes coding so far ahead of 'master' :-)

**Comment by dtaylor113** [comment]
BTW, just curious, did you test any of the blueprint functionality after making these changes?   'cause I think I'll also have to update the HTML files to refer to the new 'vm.' functions :cry:

**Comment by dtaylor113** [comment]
Ugh..yeah, all the HTML files need to be updated as well :sob: 

@chriskacerguis , @serenamarie125, I think going forward major changes like this need to be better coordinated.  Blueprints are going to be down for a few days :cry:

**Comment by AllenBW** [comment]
@dtaylor113 `gulp test` was run with no offenses, but I'll admit that to being the extent of the testing I did.

ah! nope, `$scope` in the html wasn't disturbed  :-/ totally something I can get on stat

**Comment by chriskacerguis** [comment]
@dtaylor113 just back out the change from Git.  This should not cause the downtime you are explaining.

**Comment by chriskacerguis** [comment]
@dtaylor113 feel free to add your thoughts on a PR as well :)

**Comment by dtaylor113** [comment]
@chriskacerguis  I have a SSUI PR up which needs to be rebased, plus another dev branch after that which needs to be rebased.   Don't mind me, I'm just grumbling 'cause I was rather surprised by these changes.

**Comment by dtaylor113** [comment]
@AllenBW , the $scope isn't in the HTML, just the function names which default to '$scope', so things like:  
`<button class="btn btn-primary btb-sm" type="button" ng-click="saveBlueprint()" ...`
..needs to be changed to:
`<button class="btn btn-primary btb-sm" type="button" ng-click="vm.saveBlueprint()" ...`
I appreciate you're offer to jump on this, but I'm already working on it.

**Comment by chriskacerguis** [comment]
@dtaylor113 @AllenBW are we reverting or fixing?

**Comment by dtaylor113** [comment]
For me, both.  I reverted one source code file which got completely garbled.  I'm fixing HTML and other issues.

**Comment by chriskacerguis** [comment]
@dtaylor113 ok, we will wait for your PR

cc @AllenBW

**Comment by AllenBW** [comment]
:metal: 

and again 🐼  😧 🌹

**Pull request merged**
