### PR TITLE
Removed unused titles from states

### PR DESCRIPTION
**Pull request by romanblanco**
continuation of #16 PR

@dclarizio

### CODE REVIEW

**Comment by dclarizio** [comment]
@romanblanco were your changes to aggressive?  Seems a couple of tests failed and one is looking for Dashboard text.

**Comment by dclarizio** [comment]
@romanblanco tests still failing

**Comment by romanblanco** [comment]
@dclarizio should be OK now

**Comment by himdel** [comment]
@romanblanco Are you **sure**?

Hint: https://github.com/ManageIQ/manageiq-ui-self_service/blob/master/client/app/blocks/router/router-helper.provider.js#L100

(sorry for noticing late, but we may want to revert..)

**Pull request merged**
