### PR TITLE
SDUI: Publish, Select Entry Points, Create Catalog, and Save On Nav. Away

### PR DESCRIPTION
**Pull request by dtaylor113**
Hi,
This PR brings comprises of several new features:

### Publish 

From right-hand kabob menu in blueprints list view:

image

Note: validation errors when no Catalog or Dialog selected

### Select Entry Points

From blueprint details dialog, Advanced Options, [Browse] for an entry point:

image

### Create Catlog

From blueprint details dialog, [Create Catalog] button:

image

### Save On Nav. Away

On service designer page, [ Save ] button disabled until one of the following blueprint changes detected:

- Name change
- Any blueprint detail values change
- Service Item added or removed from canvas
- Service Item dragged/moved on canvas

If one attempts to navigate away from blueprint with changes not saved, they are presented with dialog:

image

Button actions:

- Cancel: remains on designer page
- Don't Save: doesn't save any blueprint changes, navigates to new page
- Save: Saves blueprint changes, navigates to new page

### Toolbox Filtering

From designer toolbox, one can now filter available service items:

image

### CODE REVIEW

**Comment by dtaylor113** [comment]
Hi, any movement on commiting  this PR?  It's been open for over a month!  :-)
Thanks,
- Dave

**Comment by dclarizio** [comment]
@dtaylor113 sorry for the wait, but now that Darga is finalized, would like to have @himdel or @AparnaKarve do a quick review and we'll move this forward.  Thx, Dan

**Comment by dclarizio** [comment]
@dtaylor113 the good news is, PF and AngularJS versions are all updated, bad news, you need to rebase.  This should be ready to go once you do.  Thx, Dan

**Comment by dtaylor113** [comment]
Rebased and addressed some issues now that SSUI is using the currently PF release (yay!)

**Comment by dtaylor113** [comment]
Hi, if this is good to go, can someone merge this so I don't have to do another rebase!  :-)  -thanks

**Comment by dtaylor113** [comment]
Hi, any movement on this PR? -thanks

**Pull request merged**
