### PR TITLE
Refactoring/143 update npm bower dependencies

### LINKED ISSUE #143: Updates npm dependencies
Need to Clean up & updates npm dependencies.  Work started on this here: https://github.com/ManageIQ/manageiq-ui-self_service/pull/72 but, it has gone stale.

### PR DESCRIPTION
**Pull request by AllenBW**
closes #143 related to #72

There are a few dependencies we can't update (hamstrung by libs) these include:
*     "jquery": "2.1.4"
*     "angular-bootstrap": "0.13.3"
*     "lodash": "3.9.0"

Would appreciate feedback and/or lemme know if anything was missed!

@chriskacerguis @himdel  :finnadie:

### CODE REVIEW

**Comment by chriskacerguis** [comment]
So, you said "hamstrung by libs"...what libs?

**Comment by chriskacerguis** [comment]
@AllenBW So, you said "hamstrung by libs"...what libs?

**Comment by AllenBW** [comment]
@chriskacerguis patternfly is locking jquery and angular-patternfly lodash and angular-bootstrap

**Comment by chriskacerguis** [comment]
@AllenBW gotcha.  Can you create a GitHub issue for them update in their repo (post links back)

**Pull request merged**
