### PR TITLE
[EUWE] Update gettext catalog for euwe

### PR DESCRIPTION
**Pull request by mzazrivec**
Requested today by translators.

The PR also removes `maxlength` check from `.jshintrc` for the tests to pass.

### CODE REVIEW

**Comment by AllenBW** [comment]
I vote we up ` "maxparams" : 10, // {int} Max number of formal params allowed per function` to **12** to fix this build and #211 and #218

As jshint goes away next version, no point in fighting the linters here 
@chriskacerguis @mzazrivec @himdel

**Comment by AparnaKarve** [comment]
@AllenBW If`.jshintrc` was removed here : https://github.com/ManageIQ/manageiq-ui-self_service/pull/127/commits/0cb745a9a6997feaa9471ae769eede24eb978902, how come the `"maxparams" : 10` failure is still showing up?

**Comment by AllenBW** [comment]
@AparnaKarve that wasn't flagged as a go for euwe, code here (and in all the other failing euwe prs outstanding) still use jscs 
 https://github.com/mzazrivec/manageiq-ui-self_service/tree/0bcc44dbc897035f5d6c4a6f2e76ab733f011c3e

**Comment by himdel** [comment]
Agreed, no point in fighting it, I'd actually just set to 0.

**Comment by himdel** [comment]
Uh, not 0, false :-)

**Comment by AparnaKarve** [comment]
@AllenBW For some reason I assumed this commit : 0cb745a was backported to euwe as well since the backporting is usually like-for-like.
Any particular reason why we are excluding that commit for euwe and keeping it for upstream only?

**Comment by AllenBW** [comment]
@AparnaKarve i am the not right person to ask why it was excluded :P @chriskacerguis ?

**Comment by chriskacerguis** [comment]
Looks like it got lost in the euwe/conflicts that happened with @ZitaNemeckova commit.  Can we just re-add what we need?

**Comment by chriskacerguis** [comment]
@mzazrivec could you address that jshint issue, not sure what happened.

**Comment by AparnaKarve** [comment]
@chriskacerguis Did we ever plan on removing `.jshintrc` ? Or was it unintentionally removed in 0cb745a? (I'm still not clear on that)

- If it was an unintentional delete, then we'll need an upstream PR to put `.jshintrc` back in, with the `"maxparams" : 10"` rule relaxed. The upstream PR should then be backported to euwe. Once we have taken these steps,  the `"maxparams"` related failures here in this PR would be resolved.

- If it was meant to be deleted, then we'll need a euwe-specific PR to delete `.jshintrc`

Either of the above 2 actions should sync-up things between upstream and euwe-backporting.

**Comment by AllenBW** [comment]
@AparnaKarve hmm something odd is going on, all jshint and jscs has been intentionally removed from sui master here: https://github.com/ManageIQ/manageiq-ui-self_service/commit/67475e886cbd7cd470932c051ed536b53d8be6b4

if we aren't backporting eslint commits, it should definitely be restored

**Comment by chriskacerguis** [comment]
@AparnaKarve no, it should not have been removed.  

@AllenBW no worries, can we just add the files back real quick?

**Comment by himdel** [comment]
It was not removed, that's why we're hitting the failure here. 0cb745a had a rebase artifact removing it, but that change never got to #205 (correctly) so `.jshintrc` *is* in euwe and apparently supposed to be (since https://github.com/ManageIQ/manageiq-ui-self_service/pull/184 is `euwe/no`).

And yes, to make the tests pass here, we'll need to fix jshintrc in darga. That limit of 10 params is simply untenable and needs to be removed - it was never designed to work with angular's DI anyway.

@mzazrivec Could you please change that offending line (`maxparams`) in `.jshintrc` to `false`?

(BTW, @chriskacerguis this is a perfectly good example of what I'm afraid of in #204 - a perfectly good change blocked by an unrelated style check failure (granted, complicated by the fact that the old style checks are run as part of the specs but still))

**Comment by himdel** [comment]
@chessbyte it's green now :)

**Comment by chriskacerguis** [comment]
@himdel I guess I'm not following your comment.  (1) because that is talking about Code Climate, and this was a Travis failure (going to assume you mean build failures in general), but (2) I far as I see the system worked.  We got a build failure, we investigated, and we resolved in a rather quick process.  AND once we identified the issue, I was more than happy to do a merge with it red, but I wanted to make sure that others in different timezones had the opportunity to comment.  Seems to me that the system worked fine.  If you don't like the way that the system is working (which is totally cool/good to question it...maybe can you log an issue with your proposal (I don't feel that #204 is the place for that, but feel free to discuss in there) and we can discuss with the team at large)?

**Comment by himdel** [comment]
@chriskacerguis well, OK, if that's what you take from that, I'm happy with how things are :) I was just really afraid of having a policy of "jshint fails, can't merge" and wanted to make that clear :).

**Pull request merged**
