### PR TITLE
Use angular-patternfly vertical navigation directive

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
Change navigation visuals from the patternfly alt layout to the new patternfly vertical navigation. This adds a secondary navigation menu for Designer -> Blueprints. Secondary menu is also "pinnable".

image

image

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
cc @serenamarie125 @skateman @epwinchell

**Comment by epwinchell** [comment]
@miq-bot assign @dclarizio

**Comment by epwinchell** [comment]
@jeff-phillips-18 Tested. Looks great.

**Comment by epwinchell** [comment]
@miq-bot add_label enhancement

**Comment by himdel** [comment]
(Tests should pass when #118 is merged..)

**Pull request merged**
