### PR TITLE
Indicate duplicate Shopping cart items

### PR DESCRIPTION
**Pull request by himdel**
Adding a catalog item to the Shopping Cart multiple times is completely OK, even with identical data. However, sometimes that happens by accident and we need to indicate the duplicates.

   * [x] detect on "add to cart" that there is already an item in the cart that is identical (same catalog item with the same responses) in the cart, then present a modal letting them know that and allowing ok or cancel.
ssui-dup-modal

   * [x] after adding an item to the cart, change the message returned to a warning, something like "Item successfully added to cart, but it's a duplicate of an existing item".
ssui-dup-notify

   * [x] when the user goes to checkout, indicate duplicates somehow in the cart so the user knows they may have inadvertently added two identical items.
ssui-dup-indicate

   * [x] ideally support this even after reload, not strictly necessary though
```
# data obtained from the client when adding a new item
{ Catalog: "Yellow Catalog 1", CatalogItem: "Windows vApp Template 1", Description: "bar", Name: "foo", Organisation: null, Poweron: "t", networkname: "Green NAT", service_template_href: "/api/service_templates/10000000000037", vDCName: null }

# data obtained from the server when reloading
{ dialog: { dialog_Catalog: "Yellow Catalog 1", dialog_CatalogItem: "Windows vApp Template 1", dialog_Name: "foo", dialog_Description: "bar", dialog_Poweron: "t", dialog_networkname: "Green NAT" }, workflow_settings: { resource_action_id: 10000000000059, dialog_id: 10000000000013 }, src_id: 10000000000037, requester_group: "EvmGroup-super_administrator" }

# common format both are converted to
{ Catalog: "Yellow Catalog 1", CatalogItem: "Windows vApp Template 1", Description: "bar", Name: "foo", Poweron: "t", networkname: "Green NAT", service_template_href: "/api/service_templates/10000000000037" }
```

   * [x] also watch for duplicates in the interval between pushing the button and having received the server response to that action - probably best to just spin the button while doing that..
ssui-dup-spinner

---

euwe: https://bugzilla.redhat.com/show_bug.cgi?id=1377759
darga: https://bugzilla.redhat.com/show_bug.cgi?id=1380170

### CODE REVIEW

**Comment by himdel** [comment]
@chriskacerguis could you please.. :)

**Comment by chessbyte** [comment]
Euwe Backport conflict:
```sh
$ git cherry-pick -e -x -m 1 12de409                                                                     
error: could not apply 12de409... Merge pull request #199 from himdel/duplicate-cart-bz1377759
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'

$ git status
On branch euwe
Your branch is up-to-date with 'upstream/euwe'.
You are currently cherry-picking commit 12de409.
  (fix conflicts and run "git cherry-pick --continue")
  (use "git cherry-pick --abort" to cancel the cherry-pick operation)

Changes to be committed:

	modified:   client/app/components/confirmation/confirmation.directive.js
	modified:   client/app/components/notifications/notification-footer.html
	new file:   client/app/components/shopping-cart/_shopping-cart.scss
	modified:   client/app/components/shopping-cart/shopping-cart.html
	modified:   client/app/services/shopping-cart.service.js
	modified:   client/app/states/administration/profiles/profiles.html
	modified:   client/app/states/marketplace/details/details.html
	modified:   client/app/states/marketplace/details/details.state.js
	modified:   client/app/states/services/details/details.html

Unmerged paths:
  (use "git add/rm <file>..." as appropriate to mark resolution)

	both modified:   client/app/components/_components.sass
	deleted by us:   client/app/components/rules/rules-list.html

$ git diff
```

```diff
diff --cc client/app/components/_components.sass
index 83e8ed2,8c92e91..0000000
--- a/client/app/components/_components.sass
+++ b/client/app/components/_components.sass
@@@ -15,3 -15,5 +15,8 @@@
  @import 'blueprint-delete-modal/blueprint-delete-modal'
  @import 'create-catalog-modal/create-catalog-modal'
  @import 'tagging/tagging'
++<<<<<<< HEAD
++=======
+ @import 'rules/rules'
+ @import 'shopping-cart/shopping-cart'
++>>>>>>> 12de409... Merge pull request #199 from himdel/duplicate-cart-bz1377759
* Unmerged path client/app/components/rules/rules-list.html
```

**Comment by himdel** [comment]
Euwe version in https://github.com/ManageIQ/manageiq-ui-self_service/pull/209

**Comment by himdel** [comment]
Darga won't backport cleanly either - https://github.com/ManageIQ/manageiq-ui-self_service/pull/214

**Comment by chessbyte** [comment]
Backported to Euwe via https://github.com/ManageIQ/manageiq-ui-self_service/pull/209

**Comment by chessbyte** [comment]
Backported to Darga via https://github.com/ManageIQ/manageiq-ui-self_service/pull/214

**Pull request merged**
