### PR TITLE
added test coverage to codeclimate

### PR DESCRIPTION
**Pull request by chriskacerguis**

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@himdel ?

**Comment by AllenBW** [comment]
@chriskacerguis he's on pto today, response not likely... 🌴

**Comment by himdel** [comment]
I can't test it but it *looks* good.. :-)

**Comment by chriskacerguis** [comment]
As tests have passed, all have added their approval, AND because this is mostly readme file changes, I will self-merge this.

**Pull request merged**
