### PR TITLE
[WIP] Add notifications drawer and toast notifications.

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
Do not merge.

This PR adds toast notifications and a notifications drawer. 
It requires Patternfly and Angular Patternfly 3.5.1
Sample events can be created by opening the shopping cart (to be removed prior to completion).

@skateman Please take a look.

### CODE REVIEW

**Comment by skateman** [comment]
@jeff-phillips-18 could you send me some screenshots about the changes? I'm not sure what should I see...

**Comment by dclarizio** [comment]
@jeff-phillips-18 latest PF/AngularJS updates are in (#73).  This one needs a rebase.  Thx, Dan

**Comment by jeff-phillips-18** [comment]
@skateman On the title bar, click the shopping cart to create a faux-event shown in a toast notification. Click the bell to see the notifications drawer.

create_event
toast_notification
show_drawer
drawer

**Comment by jeff-phillips-18** [comment]
@serenamarie125 Please review as well

**Pull request closed without merging**
