### PR TITLE
enable scss linter in code climate

### PR DESCRIPTION
**Pull request by chriskacerguis**
enable scss linter in code climate

### CODE REVIEW

**Comment by chriskacerguis** [comment]
Enabling linting in Code Climate: https://github.com/ManageIQ/manageiq-ui-self_service/issues/215

**Comment by chriskacerguis** [comment]
@AparnaKarve could you please review and merge?

**Comment by chriskacerguis** [comment]
CC is failing due to the new checks.

**Comment by AparnaKarve** [comment]
@chriskacerguis In that case, should the CC issues be fixed here in this PR?

**Comment by chriskacerguis** [comment]
@AparnaKarve mixed feelings on that.  It didn't really touch anything related to that code, but I'll fix anyway.

**Comment by chriskacerguis** [comment]
Closing.  Superseded by https://github.com/ManageIQ/manageiq-ui-self_service/pull/229

**Pull request closed without merging**
