### PR TITLE
Refactoring/140 prune gulp tasks

### LINKED ISSUE #140: Identify and Clean up build tasks
We need to identify and clean up build tasks for this app (minifying, etc).

Each task should be documented

### PR DESCRIPTION
**Pull request by AllenBW**
# **`gulp serve-dev` renamed to `gulp serve`**

Removes:
 * gulp serve-build
 * gulp plato

This also removes isDev var from gulp serve task, since serve environment will always be dev
`gulp serve-spec` remains the same
Readme was also updated

@chriskacerguis @himdel @jeff-phillips-18 @dtaylor113 @juliancheal (<3)

closes #140

### CODE REVIEW

**Comment by AllenBW** [comment]
@miq-bot add_label technical_debt, ewue/no

**Comment by AllenBW** [comment]
@miq-bot add_label 'technical_debt', 'euwe/no'

**Comment by AllenBW** [comment]
I give up

**Comment by chriskacerguis** [comment]
@AllenBW I don't think you need the quotes.

**Pull request merged**
