### PR TITLE
Updated gulp-clean-css to latest version, 1.0.0 doesn't even exist

### PR DESCRIPTION
**Pull request by AllenBW**
Minor change, when switching the depreciated dependency I overlooked updating the version.

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@AllenBW so, I merged this, but why isn't our testing catching this stuff?

**Comment by AllenBW** [comment]
@chriskacerguis catching what? we don't test any of the gulp tasks and don't have a dependency version hound in travis. nothing to catch here really

**Comment by chriskacerguis** [comment]
I guess, the better question is what **should** the tests fail on.

**Comment by AllenBW** [comment]
@chriskacerguis I would say, tests (excluding style checks and other assisting hooks) should fail whenever functionality of the app deviates from ta previously established nominal operation.  Tests should describe the entirety of actions we expect users to perform and should be seen as a companion to any new functionality moving forward.

**Pull request merged**
