### PR TITLE
Combine about controller with navigation controller

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
This fixes issue #194

The use of the aboutModal directive inside the navigation controller
caused an override of the ‘vm’ and the toast and notification drawer
data was no longer available. This removes the aboutModal directive
and instead combines it with the navigation controller and application
html.

@chriskacerguis @ZitaNemeckova

### CODE REVIEW

**Comment by chessbyte** [comment]
Euwe Backport conflict:
```sh
$ git cherry-pick -e -x -m 1 a777387
error: could not apply a777387... Merge pull request #196 from jeff-phillips-18/fixes
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'

$ git status
On branch euwe
Your branch is up-to-date with 'upstream/euwe'.
You are currently cherry-picking commit a777387.
  (fix conflicts and run "git cherry-pick --continue")
  (use "git cherry-pick --abort" to cancel the cherry-pick operation)

Changes to be committed:

	modified:   client/app/components/navigation/navigation-contoller.js
	modified:   client/index.html

Unmerged paths:
  (use "git add <file>..." to mark resolution)

	both modified:   client/app/layouts/application.html

$ git diff
```

```diff
diff --cc client/app/layouts/application.html
index a0c238e,4757fb2..0000000
--- a/client/app/layouts/application.html
+++ b/client/app/layouts/application.html
@@@ -28,6 -31,29 +31,32 @@@
              <span class="fa" ng-class="{'fa-bell': vm.newNotifications, 'fa-bell-o': !vm.newNotifications}"></span>
            </a>
          </li>
++<<<<<<< HEAD
++=======
+         <li class="dropdown">
+           <a class="dropdown-toggle nav-item-iconic" id="aboutModal" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
+             <span class="fa pficon-help"></span>
+             <span class="caret"></span>
+           </a>
+           <ul class ="dropdown-menu" aria-labelledby="aboutModal">
+             <li>
+               <a href="/support/index?support_tab=about">
+                 {{ 'Documentation' | translate}}
+               </a>
+             </li>
+             <li>
+               <a href="http://www.manageiq.org" target="_new">
+                 ManageIQ.org
+               </a>
+             </li>
+             <li>
+               <a href="#" ng-click="vm.openAbout()">
+                 {{'About' | translate}}
+               </a>
+             </li>
+           </ul>
+         </li>
++>>>>>>> a777387... Merge pull request #196 from jeff-phillips-18/fixes
          <li dropdown>
            <a dropdown-toggle class="nav-item-iconic" title="{{ ::vm.user().userid }}">
              <i class="fa pficon-user"></i>
```

**Comment by chessbyte** [comment]
@jeff-phillips-18 @chriskacerguis Please resolve git conflict locally, make PR against euwe branch and assign that PR to me.

**Comment by jeff-phillips-18** [comment]
@chessbyte Looks like the about modal was not added this branch. If not, then this commit does not need to be cherry-picked.

**Comment by chriskacerguis** [comment]
@jeff-phillips-18 which modal are you talking about?

**Comment by jeff-phillips-18** [comment]
@chrisarcand the about modal drop drop down in SUI. This commit combines the about modal controller with the navigation controller since they would othewise conflict. When I tried to cherry-pick this commit, I found the about modal directive does not exist in the euwe branch so no need to combine 😉

**Comment by chriskacerguis** [comment]
@jeff-phillips-18 did you mean "chriskacerguis"

**Comment by jeff-phillips-18** [comment]
@chriskacerguis  @chrisarcand yes, sorry about that

**Comment by chriskacerguis** [comment]
Looks like we need to get the conflict here fixed:

https://github.com/ManageIQ/manageiq-ui-self_service/pull/127

**Comment by jeff-phillips-18** [comment]
@chriskacerguis ah yes, once that is resolved we can work to resolve this.

**Comment by chessbyte** [comment]
Now that #127 has been backported, this PR cherry-picked cleanly.
Euwe Backport details:
```sh
$ git log
commit 90b41764c2e396bef0a7f7656f29535741fb8208
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Tue Sep 27 10:17:53 2016 -0500

    Merge pull request #196 from jeff-phillips-18/fixes
    
    Combine about controller with navigation controller
    (cherry picked from commit a77738782a3ec8a65a54122ca903c1892ce66519)
```

**Pull request merged**
