### PR TITLE
added CodeClimate config with a link eslintrc

### PR DESCRIPTION
**Pull request by chriskacerguis**
added CodeClimate config with a link eslintrc

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@AllenBW @AparnaKarve can you all please take look here.

**Comment by AparnaKarve** [comment]
@chriskacerguis Was reading up the doc here https://docs.codeclimate.com/docs/eslint
Do we need `channel: "eslint-3"` ?

**Comment by chriskacerguis** [comment]
@AparnaKarve I think the suggestion version was fine, but that brings up the fact we are trying to get everything "current" (and I didn't check the rules @AllenBW put in) so I think that would be a good idea.

**Comment by chriskacerguis** [comment]
@AparnaKarve @himdel you all ok with this?

**Comment by himdel** [comment]
Sure, my only concern is the rename of `eslintrc` - the name without the extension is considered deprecated..

**Comment by chriskacerguis** [comment]
@himdel updated.  Waiting for checks to pass.

**Pull request merged**
