### PR TITLE
Add support for custom buttons with attached dialogs

### PR DESCRIPTION
**Pull request by eclarizio**
There is currently an issue where when a required field is not filled in or given, the API call still returns a 200 success, and so the SSUI returns back to the service with a message saying "Success! X field is required".

While testing this, an issue was also discovered where while ordering a service through a service template custom dialogs do not honor the required fields and allow submissions with "incomplete" forms. See git issue: #14

~~I'm also having a lot of issues with specs, so I figured I'd throw this WIP out there to see if travis works any better.~~

### CODE REVIEW

**Comment by gmcculloug** [comment]
Tested PR with @eclarizio and found a few issues:

1. Button group names are appended with " | ServiceTemplate | <service_template_id>"
2. Button groups are hidden by the UI if the screen width is decreased.  (Exacerbated by item 1)
3. When the service is loaded the Custom Buttons are fully resolved and any dynamic dialog fields are processed at that time.  The dialogs should only be resolved when the custom button is about to be displayed and the dynamic fields should be resolved at that time.

Item 1 example
image

Item 2 example
image

**Comment by eclarizio** [comment]
Depends on: https://github.com/ManageIQ/manageiq/pull/7117

**Comment by eclarizio** [comment]
@gmcculloug I've fixed the issues mentioned above, but on Friday when I rebased I ran into issues actually getting the UI up and running so I couldn't actually test. Some of the specs are also missing tests due to that setback, but I figured I'd throw up what I have if you can test it.

**Comment by eclarizio** [comment]
@gmcculloug Alright, this should be good to go, just updated with the latest. Still trying to get my environment up and working but the code is ready.

**Comment by gmcculloug** [comment]
Further testing found that refreshing a dynamic field for a custom button fails because it currently references the dialog assigned to the "provision" actions for the service's template.  The previous issues appear to be working at this point.

**Comment by eclarizio** [comment]
Currently waiting for https://github.com/ManageIQ/manageiq/pull/7147 to be un-wip'd and merged, since this now uses an API call introduced in that PR that was meant to fix the issue described above.

**Comment by eclarizio** [comment]
Reference https://github.com/ManageIQ/manageiq/pull/7330 above is an additional feature that will include the custom buttons that have been assigned via the "Automate/Customization" interface.

**Comment by AparnaKarve** [comment]
@dclarizio Verified in SSUI. LGTM :+1:

**Comment by gmcculloug** [comment]
@dclarizio Looks good.

**Pull request merged**
