### PR TITLE
updated navbar styling to match operations ui

### PR DESCRIPTION
**Pull request by epwinchell**
Old
screen shot 2016-05-06 at 10 05 49 am
screen shot 2016-05-06 at 10 05 39 am

New
screen shot 2016-05-06 at 9 51 13 am
screen shot 2016-05-06 at 10 17 30 am

### CODE REVIEW

**Comment by epwinchell** [comment]
@miq-bot add label ui, enhancement

**Comment by epwinchell** [comment]
cc @serenamarie125

**Comment by epwinchell** [comment]
@miq-bot add_label ui, enhancement

**Comment by epwinchell** [comment]
@miq-bot add_label darga/yes

**Comment by epwinchell** [comment]
@miq-bot add_label ui

**Comment by serenamarie125** [comment]
LGTM @epwinchell 
Thanks for getting this done!

**Comment by epwinchell** [comment]
@dclarizio

**Pull request merged**
