### PR TITLE
Isolate unit tests

### PR DESCRIPTION
**Pull request by AllenBW**
Relocate .spec files to `/tests`, reconfigure gulp config to support change

another notch in #121, this task removes the work of adding the mountain of code style exceptions that would be support the `.spec`s interwoven with the app 

@chriskacerguis 🌏

### CODE REVIEW

**Comment by chriskacerguis** [comment]
👍

**Comment by himdel** [comment]
What's the darga and euwe status of this PR?

**Comment by chriskacerguis** [comment]
@himdel do we need the euwe tag?  I believe that this was in there before the merge, and so it should have it in there.  I'll add the Darga tag

**Comment by himdel** [comment]
Aah, ok, could be, thanks :) adding euwe/yes to #192 then :)

**Pull request merged**
