### PR TITLE
Fix About Modal and dropdown info for downstream

### PR DESCRIPTION
**Pull request by AparnaKarve**
The About Modal and dropdown currently displays hard-coded information which works for upstream but is incorrect in a productized environment like downstream.
This PR removes those hard-coded values and instead uses the product info retrieved from the `/api` API.

Notice in the screenshots below that the `Copyright` and `Support Website` values have been fixed.

Before:
screen shot 2016-09-27 at 3 53 27 pm

screen shot 2016-09-27 at 3 55 18 pm

After:
screen shot 2016-09-30 at 2 18 00 pm

screen shot 2016-09-30 at 2 17 44 pm

### CODE REVIEW

**Comment by chriskacerguis** [comment]
Need to get this conflict resolved first: https://github.com/ManageIQ/manageiq-ui-self_service/pull/127

**Comment by chriskacerguis** [comment]
@AparnaKarve do we need to "fix" this https://github.com/ManageIQ/manageiq-ui-self_service/pull/127 before we merge this?

**Comment by AparnaKarve** [comment]
@chriskacerguis There should be no issues merging this for upstream.
As far as Euwe goes, I might have to create a Euwe PR after https://github.com/ManageIQ/manageiq-ui-self_service/pull/205 gets merged if there are conflicts.

**Comment by chessbyte** [comment]
Euwe Backport details:
```sh
$ git log
commit 5fe5b18c8ecf48ab0baf0a9d7363148d1edf7779
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Mon Oct 3 09:16:43 2016 -0500

    Merge pull request #208 from AparnaKarve/fix_about_productized_info
    
    Fix About Modal and dropdown info for downstream
    (cherry picked from commit 9efcb46b6820a7343b170b7cb4e0247ac94c338b)
```

**Pull request merged**
