### PR TITLE
Unit Tests: Moved mock data into JSON files

### PR DESCRIPTION
**Pull request by dtaylor113**
Hi, found a simple utility which allows us to read mock data from json files instead of embedding them in the unit test specs themselves.

However...I'm seeing an issue where after the unit tests finish:

`[11:32:14] Finished 'test' after 8.64 s`

It seems to pause for 5-10 seconds until it returns the prompt.  @AllenBW , @jeff-phillips-18 , could you please clone this branch/PR and please see if you are seeing this issue as well?

Thanks,
- Dave

### CODE REVIEW

**Comment by chriskacerguis** [comment]
Setting as WIP until we get the feedback requested.

**Comment by dtaylor113** [comment]
@chriskacerguis , ty!

**Comment by dtaylor113** [comment]
I'm seeing the 'pause' like every 3rd/4th run of the tests, but I'm not sure if it's my (fedora) environment.

**Comment by chriskacerguis** [comment]
Travis didn't see to have any issues.  Maybe just something local?

**Comment by dtaylor113** [comment]
@chriskacerguis , that's what I'm thinking, I keep getting 'low disk space on /home' msgs, so wonder if it's swapping or something.

**Comment by jeff-phillips-18** [comment]
@dtaylor113 It is happening for me as well MacOS

**Comment by dtaylor113** [comment]
Ok, I'll close this PR and continue to investigate a solution.

**Comment by dtaylor113** [comment]
Hmm...I switch back to 'master' branch and I'm still seeing the pause after running unit tests, so not sure if this is due to this PR.  @jeff-phillips-18 , @AllenBW  could you please verify?  -thanks!

**Comment by jeff-phillips-18** [comment]
@dtaylor113 I still see it as well 😖

**Comment by dtaylor113** [comment]
So, beginning to think this PR is NOT causing the pause after running unit tests, but need additional folks to verify.  -Thanks :-)

**Comment by dtaylor113** [comment]
Hi @AllenBW , when/if you get a moment, could you start up a recent version of SUI (not this PR), and let us know if you are seeing a pause after the unit tests run?  We're seeing a pause every 4th, or 5th, run.  -thanks :-)   We're trying to determine if the unit test 'pause' is already in the master branch (prior to this PR).

**Comment by AllenBW** [comment]
@dtaylor113 Oh yeah totally seeing that pause, we've had that for as long as I can remember.

**Comment by chriskacerguis** [comment]
@AllenBW can you make an issue to investigate that pause (please put in as much info as you can)?

**Comment by dtaylor113** [comment]
@AllenBW , thank you for checking/replying!   @chriskacerguis , I believe this PR is good to go then :-)

**Pull request merged**
