### PR TITLE
[WIP] 'About' modal

### PR DESCRIPTION
**Pull request by epwinchell**
This PR introduces the 'About' Modal to the SSUI.  
The neccessary API changes were added in the following PR: https://github.com/ManageIQ/manageiq/pull/10848
The OPS UI PR is here: https://github.com/ManageIQ/manageiq/pull/9989

https://bugzilla.redhat.com/show_bug.cgi?id=1277207
https://www.pivotaltracker.com/n/projects/1613907/stories/123185391

TODOs:
- [x] Create "?" dropdown with links to:
      - [ ] documentation
      - [ ]  support website (ManageIQ.org)
      - [x] and "About" Modal

- [x] 'About' Modal
  -  [ ]  product and version info

screen shot 2016-09-07 at 1 33 25 pm

### CODE REVIEW

**Comment by epwinchell** [comment]
@miq-bot add_label wip, enhancement

**Comment by epwinchell** [comment]
cc @AparnaKarve @ZitaNemeckova @himdel @dclarizio

**Comment by epwinchell** [comment]
@miq-bot assign @AparnaKarve

**Comment by epwinchell** [comment]
cc @serenamarie125

**Comment by serenamarie125** [comment]
@epwinchell this is looking good!

**Comment by AparnaKarve** [comment]
@ZitaNemeckova This PR demonstrates the Patternfly About Modal.
Once you have tried this PR, lets discuss on the next steps.

**Comment by chriskacerguis** [comment]
@epwinchell @AparnaKarve Where are things with this?

**Comment by AparnaKarve** [comment]
@chriskacerguis 

 @ZitaNemeckova and I are working on this in a different PR - https://github.com/ManageIQ/manageiq-ui-self_service/pull/127

I think we could close this one.

**Comment by chriskacerguis** [comment]
Closing per @AparnaKarve

**Pull request closed without merging**
