### PR TITLE
Updated .codeclimate.yml to work with new engine support

### PR DESCRIPTION
**Pull request by chriskacerguis**
Updated .codeclimate.yml to work with the new CodeClimate engines (their next generation engine) vs the existing one.  See http://blog.codeclimate.com/blog/2015/06/19/code-climate-platform/

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@AllenBW @AparnaKarve @himdel Could you please review

**Comment by himdel** [comment]
@chriskacerguis the PR could use a description ;) I have no idea what these new engines are..

**Comment by himdel** [comment]
Another thing, we probably shouldn't have merge commits in PRs, would you please rebase instead?

**Comment by chriskacerguis** [comment]
@himdel updated the description.  Will rebase.

**Comment by himdel** [comment]
@chriskacerguis thanks :) just a heads up .. you don't need to create a new PR after a rebase, just need to `git push` with `-f` ;)

**Comment by chriskacerguis** [comment]
@himdel I have an inherent distrust of ever using "-f" (git or otherwise).

**Comment by himdel** [comment]
:D well, it *is* better than having duplicate PRs..

**Pull request closed without merging**
